### ISSUE TITLE
sell should emit Transfer event

### ISSUE THREAD

**Issue by troggy** [acebusters/acebusters-economy#64]
so that etherscan shows correct balance

E.g. an address has 300k of tokens, yet etherscan shows 600k because he doesn't see outgoing tx.
![image](https://user-images.githubusercontent.com/163447/32685789-5355496e-c6a9-11e7-8f32-5553a7a2b8d8.png)

![image](https://user-images.githubusercontent.com/163447/32685790-570268b2-c6a9-11e7-8d14-bb8f082cab13.png)

**Comment by bkcninja** [comment]
There is no ERC20 transfer event in our nutz satellite contract during sell. Only a custom Sell event. Wont we need to change the nutz satellite for this?

**Comment by troggy** [comment]
unfortunatelly this is correct. 

It is a tough call: it is not good to change satellite, but later it will be hardly ever possible once NTZ is listed on exchanges.

We can fix this and do not upgrade unless we absolutely need to (hopefully this will never happen). Or we can upgrade at some point before NTZ is listed. I'm not sure

**Comment by bkcninja** [comment]
Right now we can follow this protocol if we really want to update this:-
1. Move floor to infinity. 
2. Allocate ether to the escrow council
3. Withdraw ether from the pullPayment.
4. Deploy new nutz satellite
5. Set in controller
6. Transfer back all ether to the nutz contract (can be done in the constructor itself)

**Comment by bkcninja** [comment]
I just checked this guys balance again. I see 0 nutz. And @johannbarbie pointed out that the event Transfer is just used to list addresses on etherscan and balanceOf is used to read the balances. And now that I check the balance of this guy, I can see 0 NTZ https://etherscan.io/address/0xcb51bd23930330fd96cb5646dbf9e17c87a4d769

**Comment by troggy** [comment]
> And now that I check the balance of this guy, I can see 0 NTZ

That is correct, because he sold all his NTZ and withdrew ether. Somehow etherscan now shows the right balance even though sell transactions are not shown — there are should be two OUT transactions 300k NTZ each.

**Comment by bkcninja** [comment]
True. I have anyhow made a nutz satellite change and upgrade event change in case we change our minds about changing this in the future.

**Comment by bkcninja** [comment]
We have branch fix/NutzTransferBug for whenever we want to fix this.
